# Generated by Django 5.2.6 on 2025-09-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_userlotcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLotGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lots_images/')),
                ('main', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.userlot')),
            ],
        ),
    ]
