# Generated by Django 5.2.6 on 2025-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_userlotgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlot',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
