# Generated by Django 5.2.6 on 2025-09-18 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=30, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('added_to_attachment_menu', models.BooleanField(default=False)),
                ('allows_write_to_pm', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('birthday', models.JSONField(blank=True, default=dict, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('has_left', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
