# Generated by Django 5.2.7 on 2025-10-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_welcomed',
            field=models.BooleanField(default=False),
        ),
    ]
