# Generated by Django 5.2.9 on 2025-12-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_region_parent'),
        ('users', '0004_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.region'),
        ),
    ]
