# Generated by Django 5.2.9 on 2025-12-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
