# Generated by Django 5.2.9 on 2025-12-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_carcolor_carcolortranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha"), ('en', 'English')], max_length=3)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.region')),
            ],
        ),
    ]
