# Generated by Django 5.2.9 on 2025-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=0),
        ),
    ]
