# Generated by Django 5.2.9 on 2025-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Available'), (2, 'Pending'), (3, 'Collecting passengers'), (4, 'Driving to pickup'), (5, 'Passenger onboard'), (6, 'En route'), (7, 'Completed'), (8, 'Cancelled')], default=0),
        ),
    ]
