# Generated by Django 5.2.9 on 2025-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
