# Generated by Django 5.2.9 on 2025-12-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_approved_at'),
        ('system', '0005_carcolor_carcolortranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='system.carcolor'),
            preserve_default=False,
        ),
    ]
