# Generated by Django 5.2.9 on 2025-12-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_car_color'),
        ('system', '0006_regiontranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system.carcolor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system.carmodel'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_licence_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Driver licence number'),
        ),
    ]
