# Generated by Django 5.2.9 on 2025-12-02 18:44

import birgo.classes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_car_trip_created_at_trip_driver_trip_updated_at_and_more'),
        ('users', '0004_userlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippassenger',
            name='location_a',
        ),
        migrations.RemoveField(
            model_name='trippassenger',
            name='location_b',
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_a', to='users.userlocation')),
                ('location_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_b', to='users.userlocation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, birgo.classes.models.BaseModelInterface),
        ),
        migrations.AddField(
            model_name='trippassenger',
            name='trip_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.triprequest'),
        ),
    ]
