# Generated by Django 5.2.9 on 2025-12-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_region_parent'),
        ('trips', '0003_remove_trippassenger_location_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='region_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_a', to='system.region'),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='region_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_b', to='system.region'),
        ),
    ]
