# Generated by Django 5.2.9 on 2025-12-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_triprequest_region_a_triprequest_region_b'),
        ('users', '0004_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='location_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_a', to='users.userlocation'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='location_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_b', to='users.userlocation'),
        ),
    ]
