# Generated by Django 5.2.9 on 2025-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_triprequest_location_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='people_count',
            field=models.IntegerField(default=1),
        ),
    ]
