# Generated by Django 5.2.9 on 2025-12-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_triprequest_people_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
