# Generated by Django 5.2.9 on 2025-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_triprequest_canceled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
