# Generated by Django 5.2.9 on 2025-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_triprequest_region_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of the trip', max_digits=10, null=True),
        ),
    ]
