# Generated by Django 5.2.9 on 2025-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_triprequest_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippassenger',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
