# Generated by Django 5.2.9 on 2025-12-04 12:59

import birgo.classes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_status'),
        ('trips', '0011_alter_trippassenger_seat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequestView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drivers.driver')),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.triprequest')),
            ],
            bases=(models.Model, birgo.classes.models.BaseModelInterface),
        ),
    ]
