# Generated by Django 5.2.9 on 2025-12-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_car_color_alter_car_model_and_more'),
        ('trips', '0012_triprequestview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequestview',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
